### ISSUE TITLE
Keyboard Shortcuts/Hotkeys not showing up

### ISSUE THREAD

**Issue by IJiggleYourBalls** [Ninjabrain1/Ninjabrain-Bot#123]
I downloaded the latest version of Ninjabrain bot and followed a tutorial on how to set it up. In the tutorial, they told me to change my hotkeys so I will be able to add or subtract to the outcome depending on the side of the left middle or right bars on the eye of ender. When I went there, it was completely blank. Any help would be appreciated, thanks.
<img width="661" alt="Screen Shot 2024-12-01 at 5 40 06 PM" src="https://github.com/user-attachments/assets/11397d90-6990-4296-b092-b2b3a9aae762">

**Comment by RoshanAH** [comment]
Are you by any chance on Mac or Linux? I have run into the same error.

When I run the program, there is an exception in the console:

```
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: Could not initialize class com.github.kwhat.jnativehook.GlobalScreen
	at ninjabrainbot.io.KeyboardListener$1.run(KeyboardListener.java:39)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /tmp/libJNativeHook.x86_64.so: libxkbcommon-x11.so.0: cannot open shared object file: No such file or directory [in thread "main"]
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2025)
	at com.github.kwhat.jnativehook.GlobalScreen.<clinit>(GlobalScreen.java:84)
	at ninjabrainbot.io.KeyboardListener.preInit(KeyboardListener.java:27)
	at ninjabrainbot.Main.start(Main.java:48)
	at ninjabrainbot.Main.main(Main.java:25)
```

@Ninjabrain1 It seems like JNativeHook depends on libxkbcommon. Maybe you could handle this exception by showing the user a message about this.

**Comment by Ninjabrain1** [comment]
Yeah maybe an error can be shown to the user in this case.

To fix this issue the author of JNativeHook says "Install xkbcommon with x11 support. I think it's called libxkbcommon-0.5.0 on CentOS."
see https://github.com/kwhat/jnativehook/issues/152
